on: push

jobs:
 CodeCoverage:
    runs-on: ubuntu-latest  
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: 'AUTH_SECRET'
        run: |
              ls -la
              sfdx force:auth:sfdxurl:store -f ./authurl -s -a DH3
      
      - name: TestRun      
        id: testrun
        run: |
           sfdx force:apex:test:run -l RunAllTestsInOrg -d ./ -c  -w 10 -u DH3 -r json >> result.json
          
      # Use the output from the `hello` step
       
      - id: set_var
        run: |
          content=`cat ./result.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=resultJson::$content"
      - name: passRate_fails 
        if:  fromJson(steps.set_var.outputs.resultJson).result.summary.passRate != '100%'
        run: |
             echo passRate ${{fromJson(steps.set_var.outputs.resultJson).result.summary.passRate}} not equal to '100%'
             exit 1
             
      - name: passRate_passes
        run: |
              echo testclass run successful and passRate is ${{fromJson(steps.set_var.outputs.resultJson).result.summary.passRate}}
              
      - name: testRunCoverage_fails  
        if:  fromJson(steps.set_var.outputs.resultJson).result.summary.testRunCoverage <= 85
        run: |
          echo current testRunCoverage is ${{fromJson(steps.set_var.outputs.resultJson).result.summary.testRunCoverage}} which is less than 76%
          exit 1
        
      - name: testRunCoverage_passes
        run: |
              echo testRunCoverage passes with ${{fromJson(steps.set_var.outputs.resultJson).result.summary.testRunCoverage}}%
     
      - name: orgWideCoverage_fails  
        if:  fromJson(steps.set_var.outputs.resultJson).result.summary.orgWideCoverage <= 80
        run: |
          echo failed due to current orgWideCoverage passes is ${{fromJson(steps.set_var.outputs.resultJson).result.summary.orgWideCoverage}} which is less than 80%
          exit 1
          
      - name: OWD_passes
        run: |
              echo orgWideCoverage is ${{fromJson(steps.set_var.outputs.resultJson).result.summary.orgWideCoverage}}
                
     
      - name: Jobcompletion
        run: echo completed 
