# This is a basic workflow to help you get started with Actions

name: AutoMerge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:  
      - HOTFIX
  pull_request:
    branches: 
      - HOTFIX 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
             mkdir AM
             cd AM
             git init
             git clone https://${{ secrets.TOKEN }}@github.com/Gnanasekar-m/POC.git 
             
             
      - name: Merge
        run: |    
             cd AM/POC
             git fetch
             git config pull.rebase false
             git checkout HOTFIX
             git checkout main
             git pull
             git merge HOTFIX main
             echo merged
