# This is a basic workflow to help you get started with Actions

name: AutoMerge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:  
      - HOTFIX
  pull_request:
    branches: 
      - HOTFIX 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT-SVN
        run: |
             mkdir AM
             cd AM
             git init
             git clone https://${{ secrets.TOKEN }}@github.com/Gnanasekar-m/POC.git 
            
             
      - name: COMMIT-ID
        run: |    
             cd AM/POC
             git config --global user.email "saykarclick@gmail.com"
             git config --global user.name "gnanasekarhero"
             git fetch
             git config pull.rebase false
             git checkout HOTFIX 
             echo ${{ github.sha }} > ID.txt
             
      - uses: pCYSl5EDgo/cat@master
        id: gitlog
        with:
         path: AM/POC/ID.txt

      - run: |
            echo  $TEXT
        env:
         TEXT: ${{ steps.gitlog.outputs.text }}
      
      - name: MERGE-HOTFIX
        run: |
            cd AM/POC
            git checkout DEV 
            git cherry-pick ${{ steps.gitlog.outputs.text }}  
            git commit -am "HOTFIX"
            git push -f
            git checkout STAGING 
            git cherry-pick ${{ steps.gitlog.outputs.text }}  
            git commit -am "HOTFIX"
            git push -f
            echo MERGED-HOTFIX-DEV&STAGING
