on:
  workflow_dispatch:
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
     - name: Create an incremental tag
       uses: aurestic/incremental-tag@1.0.8
       with:
         flag_branch: tag
         message:  tagname
         prev tag:  pick
