name: CI

on:
  push:
    branches: 
      - main

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: 'AUTH_SECRET'
        run: |
              ls -la
              sfdx force:auth:sfdxurl:store -f ./authurl -s -a DEVHUB
          
     # - name: Scratch Org create
     # run: |
     #     sfdx force:project:create -n CC
     #    cd CC && sfdx force:org:create -s -f  config/project-scratch-def.json -v DEVHUB -a so1 -d 1
             
      - name: Push to Org
        run: |
             cd All_Component_DX && sfdx force:source:deploy -m ApexClass -u DEVHUB
        
      - name: Test Run
        run: |
            sfdx force:apex:test:run -l RunLocalTests -c --resultformat=--json -w 10 -u DEVHUB
       
              
