name: CI

on:
  push:
    branches: 
      - main

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: 'AUTH_SECRET'
        run: |
              ls -la
              sfdx force:auth:sfdxurl:store -f ./authurl -s -a DEVHUB
          
      - name: Scratch Org create
        run: |
             cd All_Component_DX && sfdx force:org:create -s -f  config/project-scratch-def.json -v DEVHUB -a so1 -d 30
             
      - name: push it
        run: |
             cd All_Component_DX && sfdx force:source:push -u so1
        
      - name: Run test in Devhub
        run: |
            sfdx force:apex:test:run -n TemperatureConverterTest -c -r human -w 10 -u so1      
             
              
