name: codecoverage

on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: 'AUTH_SECRET'
        run: 
            git clone https://github.com/Gnanasekar-m/POC.git
            ls -la
            cd POC && sfdx force:auth:sfdxurl:store -f ./authurl -s -a DEVHUBSEKAR
      
