name: codecoverage

on:
  push:
    branches: 
      - main

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: 'AUTH_SECRET'
        run: |
              ls -la
              cd All_Component_DX && sfdx force:org:create -s -f  config/project-scratch-def.json -v DEVHUB -a so1 -d 30
      
