name: codecoverage

on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: 'Convert Metadata'
        run: sfdx force:auth:sfdxurl:store -f ./authurl -s -a DEVHUBSEKAR
      
