name: PMD Source Code Analyzer 

on: [push]

jobs:
  pmd:
  
    runs-on: windows-latest
    
    steps:
      - uses: sfdx-actions/setup-pmd@v1
      - name: run-pmd
        run: pmd-bin-6.28.0 3/bin/pmd.bat pmd -d ./force-app/main/default/classes -f text -R POC/pmd-apex/src/main/resources/rulesets/apex/security.xml 
