name: PMD Source Code Analyzer on Push

on: [push]

jobs:
  pmd:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: sfdx-actions/setup-pmd@v1
      - name: run-pmd
        run: | 
          cd $HOME        
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.28.0/pmd-bin-6.28.0.zip
          unzip pmd-bin-6.28.0.zip
          alias pmd="$HOME/pmd-bin-6.28.0/bin/run.sh pmd"
          ls -la
          cd pmd-bin-6.28.0\bin\
          pmd.sh -d .\force-app\main\default\classes -f html -R java-unusedcode
          pmd -d ./force-app/main/default/classes -R category/apex/design.xml -f text
        shell: bash
