name: PMD Source Code Analyzer on Push

on: [push]

jobs:
  pmd:
  
    runs-on: windows-latest
    
    steps:
      - uses: sfdx-actions/setup-pmd@v1
      - name: run-pmd
        run: C:\>pmd-bin-6.28.0 3\bin\pmd.bat -d ./force-app/main/default/classes -R  ./pmd-apex/src/main/resources/rulesets/apex/style.xml -f text
