name: PMD Source Code Analyzer on Push

on: [push]

jobs:
  pmd:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: sfdx-actions/setup-pmd@v1
      - name: run-pmd 
        run: | 
          cd $HOME        
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.28.0/pmd-bin-6.28.0.zip
          git clone https://github.com/Gnanasekar-m/POC.git
          unzip pmd-bin-6.28.0.zip
          alias pmd="$HOME/pmd-bin-6.28.0/bin/run.sh pmd"
          pwd | cd ${GITHUB_WORKSPACE}/ | ls -la
          pmd -d .\force-app\main\default\classes -R ${GITHUB_WORKSPACE}/POC/pmd-apex/src/main/resources/category/apex/design.xml -f html
        shell: bash
 
