name: PMD Source Code Analyzer on Push

on: [push]

jobs:
  pmd:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: sfdx-actions/setup-pmd@v1
      - name: run-pmd
        run: pmd-bin-6.19.0/bin/run.sh pmd -dir ./force-app/main/default/classes -f html -rulesets rulesets/java/quickstart.xml,category/java/codestyle.xml
