
name: IC

on:
  workflow_dispatch:

jobs:
 CodeCoverage:
    runs-on: ubuntu-latest  
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: Delta
        run: |
              sfdx update
              echo ${{ github.event.pull_request.head.sha }}
              git checkout ${{ github.event.pull_request.head.sha }}
