
name: IC

on:
  push

jobs:
 CodeCoverage:
    runs-on: ubuntu-latest  
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: Delta
        run: |
              wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
              mkdir sfdx
              tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
              ./sfdx/install
              git checkout ${{ github.event.pull_request.head.sha }}
              echo ${{ github.event.pull_request.head.sha }}

