on: push

jobs:
 ApexCodeCoverage:
    runs-on: ubuntu-latest  
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: 'AUTH_SECRET'
        run: |
              ls -la
              sfdx force:auth:sfdxurl:store -f ./authurl -s -a DEVHUB
      
      - name: testrun       
        id: testrun
        run: |
           sfdx force:apex:test:run -l RunLocalTests -c  -w 10 -u DEVHUB -r json >> result.json
          
      # Use the output from the `hello` step
   
       
      - id: set_var
        run: |
          content=`cat ./result.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=resultJson::$content"
          
          rate=fromJson(steps.set_var.outputs.resultJson).result.summary.failRate
          echo "::set-output name=rate::$rate"
          run: echo "::set-env name=DAY_OF_WEEK::$( date +%a )"
          run: echo "Somebody has a case of the mondays!"
          if: env.DAY_OF_WEEK == 'Mon'
          run: echo "This runs every day..."
      
      - name: Fail_Rate    
        
        if: ${{fromJson(steps.set_var.outputs.rate)}} = 0
        run: |
             echo failRate ${{fromJson(steps.set_var.outputs.resultJson).result.summary.failRate}}
             exit 1
             
      - name: testRunCoverage    
        if:  ${{ fromJson(steps.set_var.outputs.resultJson).result.summary.testRunCoverage }} < 80
        run: |
           echo ${{fromJson(steps.set_var.outputs.resultJson).result.summary.testRunCoverage}}
           exit 1
      - name: orgWideCoverage    
        if: ${{ fromJson(steps.set_var.outputs.resultJson).result.summary.orgWideCoverage }} < 90
        run: |
          echo ${{fromJson(steps.set_var.outputs.resultJson).result.summary.orgWideCoverage}}
          exit 1
      
      - name: Jobcompletion
        run: echo completed 
       
     
          
