name: Npm

on: push
jobs:
 Npm:
    runs-on: ubuntu-latest 
    
    steps:
    - name: clone
      run: |
        git clone https://github.com/Gnanasekar-m/POC.git 
        cd POC
        ls
        npm install
        npm run sf-build
        npm test

    steps:
    - name: clone
       run: |
        cd POC/DCX
        npm install
        npm run sf-build
        npm test





