name: Npm

on: push
jobs:
 Npm:
    runs-on: ubuntu-latest 
    
    steps:
    - name: clone
      run: |
        git clone https://github.com/Gnanasekar-m/POC.git 
        cd POC
        ls
        npm install
        npm run sf-build
        npm test
 
    - name: clone
      run: |
         cd POC/dc
         npm install
         npm run sf-build
         npm test





