name: Npm

on: push
jobs:
 Npm:
    runs-on: ubuntu-latest 
    
    steps:
    - name: npm install, build and test
      run: |
        git clone https://github.com/Gnanasekar-m/POC.git 
        ls
        cd DCX
        npm install
        npm run sf-build
        npm test




