name: Npm

on:
  workflow_dispatch:
jobs:
 Npm:
    runs-on: ubuntu-latest 
    
    steps:
    - name: clone
      run: |
        git clone https://github.com/Gnanasekar-m/POC.git 
        
    - name: clone
      run: |
         cd POC/dc
         npm install
         npm run sf-build
         npm test





