
name: IncrementChange

on:
  push

jobs:
 CodeCoverage:
    runs-on: ubuntu-latest  
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: Delta
        run: |
             git clone https://github.com/Gnanasekar-m/POC.git
             cd POC
             git diff-tree --no-commit-id --name-only -r ${{ github.sha }} > text.txt
             cat ./text.txt
             pwd
             ls
             
      - uses: pCYSl5EDgo/cat@master
        id: hello
        with:
           path: POC/text.txt
             
      - run: echo $TEXT
        env:
         TEXT: ${{ steps.hello.outputs.text }}
         
      - name: Parse
        run: sed -e 's/\s\+/,/g' POC/text.txt > POC/result.txt
        
      - uses: pCYSl5EDgo/cat@master
        id: result
        with:
           path: POC/result.txt
     
      - run: echo $TEXT
        env:
         TEXT: ${{ steps.hello.outputs.result }}
          
       
             

              

