
name: IncrementChange

on:
  push

jobs:
 IncrementChange:
    runs-on: ubuntu-latest  
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: Delta
        run: |
             git clone https://github.com/Gnanasekar-m/POC.git
             cd POC
             git diff-tree --no-commit-id --name-only -r ${{ github.sha }} > text.txt
             grep -v "cls-meta.xml" text.txt
             grep -v "trigger-meta.xml" text.txt
             sed -i 'cls-meta.xml' text.txt
             sed -i 'trigger-meta.xml' text.txt

      - uses: pCYSl5EDgo/cat@master
        id: hello
        with:
         path: POC/text.txt

      - run: |
            echo Before replace
            echo $TEXT
        env:
         TEXT: ${{ steps.hello.outputs.text }}
      
      - name: Find and Replace
        uses: shitiomatic/str-replace@master
        with:
          find: '\s'
          replace: ","
          include: POC/text.txt
        
      - uses: pCYSl5EDgo/cat@master  
        id: poc
        with:
           path: POC/text.txt
      
        
      - run: echo $TEXT
        env:
         TEXT: ${{ steps.poc.outputs.text }}

      - name: cls-meta
        if: contains(steps.poc.outputs.text , 'cls-meta.xml') || contains(steps.poc.outputs.text , 'trigger-meta.xml')
        run: |
          grep -v "cls-meta.xml" text.txt
          grep -v "trigger-meta.xml" text.txt

        env:
         TEXT: ${{ steps.poc.outputs.text }}
  


            
          
       
             

              

