
name: IncrementChange

on:
  push

jobs:
 IncrementChange:
    runs-on: ubuntu-latest  
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: Delta
        run: |
             git clone https://github.com/Gnanasekar-m/POC.git
             cd POC
             git diff-tree --no-commit-id --name-only -r ${{ github.sha }} > text.txt
             sed 's/ /,/g' text.txt
         
             
      - uses: pCYSl5EDgo/cat@master
        id: hello
        with:
         path: POC/text.txt

      - run: |
             sed 's/ /,/g' POC/text.txt > log.txt
             echo $TEXT
        env:
         TEXT: ${{ steps.hello.outputs.text }}
      - uses: pCYSl5EDgo/cat@master  
        id: hello
        with:
           path: text.txt
      
        
      - run: echo $TEXT
        env:
         TEXT: ${{ steps.log.outputs.log }}
          
       
             

              

