
name: IncrementChange

on:
  push

jobs:
 IncrementChange:
    runs-on: ubuntu-latest  
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: Checkout
        run: |
             git clone https://github.com/Gnanasekar-m/POC.git
      - name: diff-tree
        run: |       
             cd POC
             git diff-tree --no-commit-id --name-only -r ${{ github.sha }} > log.txt
             grep -v "yml" log.txt > yml.txt
             sed 's/trigger-meta.xml*/trigger/g' yml.txt > trigger.txt 
             sed 's/cls-meta.xml*/cls/g' trigger.txt  > cls.txt
          
      - uses: pCYSl5EDgo/cat@master
        id: gitlog
        with:
         path: POC/cls.txt

      - run: |
            echo Before replace
            cat "POC/cls.txt"
            echo $TEXT
        env:
         TEXT: ${{ steps.gitlog.outputs.text }}
      
      - name: Find and Replace-comma and double quote
        uses: shitiomatic/str-replace@master
        with:
          find: '\s'
          replace: ","
          include: POC/cls.txt
     
      - run: |
            sed '$ s/,$/"/' "POC/cls.txt" > text.txt
            echo $TEXT

      - uses: pCYSl5EDgo/cat@master  
        id: Log
        with:
           path: POC/text.txt
      - run: |
             echo Replaced with comma and double quote
             echo $TEXT 

        env:
         TEXT: ${{ steps.Log.outputs.text }}

      - name: cls-meta or trigger
        if: contains(steps.Log.outputs.text , 'cls') || contains(steps.Log.outputs.text , 'trigger')
        run: |
             ${{ steps.Log.outputs.text }}

      
      - name : deploy to org
        run: |
            sfdx force:auth:sfdxurl:store -f ./authurl -s -a DH3
            sfdx force:source:deploy -p "${{ steps.Log.outputs.text }} -u DH3
              
           
  


            
          
       
             

              

